/* eslint-disable sort-keys-fix/sort-keys-fix */
/* eslint-disable sort-keys */
import type { StrumPattern } from "./types";

const library: Record<string, StrumPattern> = {
  "d d d d -1/8": {
    noteLength: "1/8",
    strums: [
      { direction: "down" },
      { variant: "pause" },
      { direction: "down" },
      { variant: "pause" },
      { direction: "down" },
      { variant: "pause" },
      { direction: "down" },
      { variant: "pause" },
    ],
  },
  "d  d u  ud u-1/8t": {
    noteLength: "1/8 triplet",
    strums: [
      { direction: "down" },
      { variant: "pause" },
      { variant: "pause" },
      { direction: "down" },
      { variant: "pause" },
      { direction: "up" },
      { variant: "pause" },
      { variant: "pause" },
      { direction: "up" },
      { direction: "down" },
      { variant: "pause" },
      { direction: "up" },
    ],
  },
  "d d d du-1/8": {
    noteLength: "1/8",
    strums: [
      { direction: "down" },
      { variant: "pause" },
      { direction: "down" },
      { variant: "pause" },
      { direction: "down" },
      { variant: "pause" },
      { direction: "down" },
      { direction: "up" },
    ],
  },
  "d d dudu-1/8": {
    noteLength: "1/8",
    strums: [
      { direction: "down" },
      { variant: "pause" },
      { direction: "down" },
      { variant: "pause" },
      { direction: "down" },
      { direction: "up" },
      { direction: "down" },
      { direction: "up" },
    ],
  },
  "d dud du-1/8": {
    noteLength: "1/8",
    strums: [
      { direction: "down" },
      { variant: "pause" },
      { direction: "down" },
      { direction: "up" },
      { direction: "down" },
      { variant: "pause" },
      { direction: "down" },
      { direction: "up" },
    ],
  },
  "d dududu-1/8": {
    noteLength: "1/8",
    strums: [
      { direction: "down" },
      { variant: "pause" },
      { direction: "down" },
      { direction: "up" },
      { direction: "down" },
      { direction: "up" },
      { direction: "down" },
      { direction: "up" },
    ],
  },
  "d uMArdxA-1/16t": {
    noteLength: "1/16 triplet",
    strums: [
      { direction: "down", heading: "x" },
      { variant: "pause" },
      { direction: "up", heading: "^" },
      { variant: "muted" },
      { variant: "accent" },
      { variant: "rest" },
      { direction: "down" },
      { variant: "x" },
      { variant: "A" },
    ],
  },
  "d uMArdxA-1/8": {
    noteLength: "1/8",
    strums: [
      { direction: "down", heading: "x" },
      { variant: "pause" },
      { direction: "up", heading: "^" },
      { variant: "muted" },
      { variant: "accent" },
      { variant: "rest" },
      { direction: "down" },
      { variant: "x" },
      { variant: "A" },
    ],
  },
  "d ud ud ud u-1/8t": {
    noteLength: "1/8 triplet",
    strums: [
      { direction: "down" },
      { variant: "pause" },
      { direction: "up" },
      { direction: "down" },
      { variant: "pause" },
      { direction: "up" },
      { direction: "down" },
      { variant: "pause" },
      { direction: "up" },
      { direction: "down" },
      { variant: "pause" },
      { direction: "up" },
    ],
  },
  "dddddddd-1/8": {
    noteLength: "1/8",
    strums: [
      { direction: "down" },
      { direction: "down" },
      { direction: "down" },
      { direction: "down" },
      { direction: "down" },
      { direction: "down" },
      { direction: "down" },
      { direction: "down" },
    ],
  },
  "dudududu-1/8": {
    noteLength: "1/8",
    strums: [
      { direction: "down" },
      { direction: "up" },
      { direction: "down" },
      { direction: "up" },
      { direction: "down" },
      { direction: "up" },
      { direction: "down" },
      { direction: "up" },
    ],
  },
};

export default library;
